[package]
name = "py-rs"
version = "0.0.1"
authors = ["Nobuaki Mochizuki"]
edition = "2018"
#crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = "0.12.3"
#ndarray = "0.13"
#numpy = "0.12.1"
