[package]
name = "py-rs"
version = "0.0.1"
authors = ["nmochizuki"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = "0.12.3"
ndarray = "0.13"
numpy = "0.12.1"
